[package]

name = "strainm"
version = "0.1.0"
authors = ["Rhys Newell <r.newell@uq.net.au>"]
license = "GPL-3.0"
description = "Strain resolver for metagenomics"
homepage = "https://github.com/rhysnewell/StrainM"
repository = "https://github.com/rhysnewell/StrainM"
documentation = "https://github.com/rhysnewell/StrainM"
readme = "README.md"
exclude = [ # Max upload is 10MB, as of writing test data was 15MB
  "tests/*"
]

[dependencies]
rusty-machine = "0.5.4"
bio = "0.25.*"
rust-htslib = "0.22.*"
clap = "2.*"
log = "0.4.*"
env_logger = "0.6.*"
nix = "0.13.*"
tempdir = "0.3.*"
tempfile = "3.0.*"
ansi_term = "0.11"
lazy_static = "1.3.0"
rand = "0.6.*"
simhash = "0.2"

[dev-dependencies]
assert_cli = "0.6.*"
